version: '3.8'

services:
  project-application:
    image: webapp
    build: applications/.
    ports:
      - 8081:8080
    volumes:
      - project_data:/var/lib/data
    networks: 
      - common-network

volumes:
  project_data:
    driver: local

networks:
  common-network:
    driver: bridge