apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: unity
spec:
  params:
    - description: The semantic version identifier
      name: imagetag
    - description: The version tag name identifier
      name: tagname
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          imagetag: $(tt.params.imagetag)
          tekton.dev/pipeline: unity-release
        name: unity-deploy-$(uid)
      spec:
        params:
          - name: imagetag
            value: $(tt.params.imagetag)
          - name: tagname
            value: Unity_Grant_Manager_$(tt.params.imagetag)
        pipelineRef:
          name: unity-release
        serviceAccountName: pipeline
        workspaces:
          - emptyDir: {}
            name: unity-settings
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: unity
spec:
  params:
    - name: imagetag
      value: $(body.imagetag)
    - name: token
      value: $(header.b937c1bb-6794-4884-b930-d287d4a2c67d)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: unity
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: unity
      template:
      ref: unity
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: unity
  name: el-unity
spec:
  host: el-unity-c57ee7-dev.apps.silver.devops.gov.bc.ca
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-unity
    weight: 100
  wildcardPolicy: None
