# This is a workflow that is either manually or PR merge to "dev" triggered on repository push events
name: Dev - Build
on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'database/**'
      - 'documentation/**'
      - 'openshift/**'
      - 'COMPLIANCE.yaml'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'SECURITY.md'
  # Allow manual triggering
  workflow_dispatch:

# Repository secrets OPENSHIFT_TOKEN_{DEV|TEST|PROD|TOOLS}
# Repository variables VERSION_MAJOR 0 VERSION_MINOR 1 VERSION_PATCH 1
# Repository commit short sha revision
env:
  OPENSHIFT_CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  OPENSHIFT_AUTH_TOKEN: ${{secrets.OPENSHIFT_TOKEN_DEV}}
  RELEASE_VERSION: ${{vars.VERSION_MAJOR}}.${{vars.VERSION_MINOR}}.${{vars.VERSION_PATCH}}
jobs:
  # This workflow contains a job called  "Build" 
  Build:
    runs-on: ubuntu-latest
    outputs: 
      PROJECT: ${{steps.project.outputs.TARGET_PROJECT}}
    steps:
    - uses: actions/checkout@v3
    - name: Get commit sha_short
      id: commit
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Get buildArgs
      run:  |
        echo "buildArgs UNITY_BUILD_VERSION: ${{env.RELEASE_VERSION}}, UNITY_BUILD_REVISION: ${{ steps.commit.outputs.sha_short }}"
    - name: Build Docker mages
      run: |
        rm -f ./docker-compose.override.yml
        docker compose build
      working-directory: ./applications/Unity.GrantManager
    - name: Connect to OpenShift API
      id: project
      run: |
        oc login --token=${{env.OPENSHIFT_AUTH_TOKEN}} --server=${{env.OPENSHIFT_CLUSTER}}
        echo "PROJECT=$(oc project | grep -oE '[0-9a-z]*-[dev\|test\|prod\|tools]*')" >> $GITHUB_OUTPUT
        oc registry login
    - name: Push build images to OpenShift container registry
      run: | 
        echo project = ${{steps.project.outputs.PROJECT}}
        docker tag unity-grantmanager-web image-registry.apps.silver.devops.gov.bc.ca/${{steps.project.outputs.PROJECT}}/unity-grantmanager-web:github-latest
        docker tag unity-grantmanager-dbmigrator image-registry.apps.silver.devops.gov.bc.ca/${{steps.project.outputs.PROJECT}}/unity-grantmanager-dbmigrator:github-latest
