# This is a basic workflow that is manually triggered

name: Manual Tag Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
  # Allows external webhook trigger
  repository_dispatch:
    types: [webhook]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Custom_tag"
  Custom_tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: '0'
    - name: Get current date
      id: date
      run: echo "date=$(date +'%B %e, %Y')" >> $GITHUB_OUTPUT
    - name: Generate Git Tag
      id: generate_tag
      run: |
        VERSION_PREFIX="v"
        VERSION_MAJOR_MINOR="0.1"
        VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
        if [ -z "$VERSION_PATCH" ]; then
          VERSION_PATCH=0
        else
          VERSION_PATCH=$((VERSION_PATCH + 1))
        fi
        NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
        echo "Generated new tag: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo "TAG_MESSAGE=Dev to Test - ${{ steps.date.outputs.date }}" >> $GITHUB_ENV
    - name: Test with environment variables
        echo "TAG_NAME=$TAG_NAME" >> >> $GITHUB_ENV
      run: echo Tag $TAG_NAME Message $TAG_MESSAGE
      env:
        TAG_NAME: TIDDCMS_${{ env.NEW_TAG }}
        TAG_MESSAGE: Dev to Test - ${{ steps.date.outputs.date }}
    - name: Push Git Tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"
        git tag $NEW_TAG -m "$TAG_MESSAGE"
        git push origin $NEW_TAG
    - name: Push Alert to Teams
      run: |
        echo tag $NEW_TAG -m "$TAG_MESSAGE"
        curl -H "Content-Type: application/json" --data-raw "{\"text\":\"Release_v0.1.x_deployment_Test_November_1_2023\"}" -X POST -k https://bcgov.webhook.office.com/webhookb2/fa08bb89-7d55-40d9-a468-d33f44399a61@6fdb5200-3d0d-4a8a-b036-d3685e359adc/IncomingWebhook/9558b1d617674555abc2cc276f9c958e/730754e7-686e-4bfa-b646-16afda18661b
    # Add your build, test, and deploy steps here
